[package]
name = "bevy_networking_simple"
version = "0.5.0"
authors = ["Neikos <neikos@neikos.email>"]
edition = "2018"
description = "A simple networking plugin for Bevy"
readme = "README.md"
repository = "https://github.com/CabbitStudios/bevy_networking_simple"
license = "MIT"
categories = ["game-development", "network-programming"]
autoexamples = false

[badges]
maintenance = { status = "actively-developed" }

[[example]]
name = "client"

[[example]]
name = "server"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5", features = [], default-features = false }
bincode = "1.3.2"
crossbeam-channel = "0.5.0"
dashmap = "4.0.2"
derive_more = "0.99.13"
downcast-rs = "1.2.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "1.0.24"
tokio = { version = "1.4.0", features = ["net", "io-util", "sync", "rt-multi-thread"] }
typetag = "0.1.7"

[dev-dependencies]
bevy = { version = "0.5" }
